<a href="https://colab.research.google.com/github/25wh1a05ae-ui/NASSCOM/blob/main/WEEK2/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


numpy operations
objectives

Array creation shortcuts

Aggregation functions (sum, mean, etc.)

Sorting and searching

Reshaping and flattening

Broadcasting

Conditional operations

Copying vs. viewing arrays

Stacking and splitting arrays

indexing and slicing with array

In [35]:
import numpy as np


In [36]:
arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)



Array using arange: [0 2 4 6 8]


In [37]:
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)



Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [38]:
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

# flatten(): Convert multi-dimensional array to 1D
print("Flattened version:", arr3.flatten())


Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [39]:
data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)


Original Data:
 [[5 8 9]
 [2 4 6]]


In [40]:
print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))

Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9


In [41]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))                       # Minimum value
print("Standard Deviation:", np.std(data))

Index of max value (flattened): 2
Min value: 2
Standard Deviation: 2.3570226039551585


In [42]:
a = np.array([3, 1, 7, 2, 9])
print("Original Array:", a)



Original Array: [3 1 7 2 9]


In [43]:
# Sort array values
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)

# Find indices where condition is True (value > 4)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])

Sorted Array: [1 2 3 7 9]
Indices where value > 4: (array([2, 4]),)
Values > 4: [7 9]


In [44]:
A = np.array([[1, 2], [3, 4]])  # 2x2 matrix
B = np.array([10, 20])          # 1D array with 2 elements

print("Matrix A:\n", A)
print("Vector B:", B)


Matrix A:
 [[1 2]
 [3 4]]
Vector B: [10 20]


In [45]:
C = A + B
print("Broadcasted Addition Result:\n", C)

Broadcasted Addition Result:
 [[11 22]
 [13 24]]


🔹 5. CONDITIONAL OPERATIONS

In [46]:
nums = np.array([1, 2, 3, 4, 5])

# Create boolean mask for condition nums > 3
mask = nums > 3
print("Mask (nums > 3):", mask)


Mask (nums > 3): [False False False  True  True]


In [47]:
# Use mask to filter values
filtered = nums[mask]
print("Filtered values:", filtered)

# np.where: apply conditional logic
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)

Filtered values: [4 5]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [48]:
arr_orig = np.array([10, 20, 30])

# Creating a view (shares memory)
arr_view = arr_orig[:]
arr_view[0] = 99  # This change affects original
print("Original After View Change:", arr_orig)


Original After View Change: [99 20 30]


In [49]:
# Creating a copy (independent)
arr_copy = arr_orig.copy()
arr_copy[0] = 55  # This does NOT affect original
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)

Original After Copy Change: [99 20 30]
Copy: [55 20 30]


🔹 7. STACKING AND SPLITTING

In [50]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Vertical stack (as rows)
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [51]:
# Horizontal stack (as columns)
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)

# Split an array into 3 sub-arrays
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)


Horizontal Stack:
 [1 2 3 4 5 6]
Split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


8. RANDOM NUMPY FUNCTIONS

In [52]:
# Random integers from 0 to 100 in 3x3 matrix
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)

# Random values from standard normal distribution (mean=0, std=1)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)

Random Integers:
 [[92 14 71]
 [60 20 82]
 [86 74 74]]
Random Normal Distribution:
 [[ 0.27904129  1.01051528 -0.58087813 -0.52516981]
 [-0.57138017 -0.92408284 -2.61254901  0.95036968]]


In [53]:
# Random sampling from a custom list
choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)

# Setting a seed ensures reproducible random results
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())


Random Choices: [1 5 5 5 3]
Seeded Random Number: 0.3745401188473625


🔹 9. INDEXING AND SLICING WITH ARRAYS


In [54]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)

# Access single elements by index
print("Element at index 0:", arr[0])        # 10
print("Element at last index:", arr[-1])    # 60


Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60


In [55]:
# Slice elements [start:stop] (stop is exclusive)
print("Slice from index 1 to 4:", arr[1:4])  # [20, 30, 40]

# Slice with step
print("Every second element:", arr[::2])     # [10, 30, 50]

# Reverse array
print("Reversed array:", arr[::-1])

Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


🔹 10A. 2D ARRAY INDEXING AND SLICING

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

# Access element at row 1, column 2
print("Element at (1,2):", matrix[1, 2])  # 6

# Get entire first row
print("First row:", matrix[0, :])  # [1, 2, 3]

# Get entire second column
print("Second column:", matrix[:, 1])  # [2, 5, 8]

# Slice sub-matrix (top-left 2x2 block)
print("Top-left 2x2 block:\n", matrix[:2, :2])  # [[1,2],[4,5]]



🔹 10B. BOOLEAN INDEXING

In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30])

# Create a boolean mask for values > 15
mask = arr > 15
print("Boolean Mask:", mask)

# Use mask to filter elements
print("Values greater than 15:", arr[mask])  # [20, 25, 30]

# Combine conditions
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])  # [20, 30]