<a href="https://colab.research.google.com/github/25wh1a05ae-ui/NASSCOM/blob/main/WEEK2/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("------------------------------------")

# =====================================================
# Task 1: Basic Pandas Functions
# =====================================================
print("\n--- Task 1 ---")

# 1.1 Create Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create NumPy array
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert to DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("Series:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)


# =====================================================
# Task 2: Synthetic Data Generation
# =====================================================
print("\n--- Task 2 ---")

df_sales = pd.DataFrame({
    "Date": pd.date_range("2023-01-01", periods=100),
    "Region": np.random.choice(["East", "West", "North", "South"], 100),
    "Product": np.random.choice(["Laptop", "Mouse", "Keyboard", "Monitor"], 100),
    "Sales": np.random.randint(100, 1001, 100),
    "Quantity": np.random.randint(1, 11, 100)
})

# Introduce 5 NaN values in Sales
sales_nan = np.random.choice(df_sales.index, 5, replace=False)
df_sales.loc[sales_nan, "Sales"] = np.nan

# Introduce 3 NaN values in Quantity
quantity_nan = np.random.choice(df_sales.index, 3, replace=False)
df_sales.loc[quantity_nan, "Quantity"] = np.nan

print(df_sales.head())


# =====================================================
# Task 3: Indexing and Slicing
# =====================================================
print("\n--- Task 3 ---")

# 3.1
df3_1 = df_sales[["Region", "Sales"]]

# 3.2
df3_2 = df_sales[df_sales["Product"] == "Laptop"]

# 3.3
df3_3 = df_sales[(df_sales["Region"] == "East") &
                 (df_sales["Sales"] > 500)]

# 3.4
monitor_index = df_sales[df_sales["Product"] == "Monitor"].index[0]

val3_4 = df_sales.loc[monitor_index, "Sales"]

# Using iloc
val3_4_iloc = df_sales.iloc[monitor_index]["Sales"]

print(df3_1.head())
print(df3_2.head())
print(df3_3.head())
print("Sales using loc:", val3_4)
print("Sales using iloc:", val3_4_iloc)


# =====================================================
# Task 4: Data Cleaning
# =====================================================
print("\n--- Task 4 ---")

# 4.1 Missing values count
missing_counts4_1 = df_sales.isnull().sum()

# 4.2 Fill missing Sales with mean
df4_2_filled = df_sales.copy()

mean_sales = df4_2_filled["Sales"].mean()

df4_2_filled["Sales"] = df4_2_filled["Sales"].fillna(mean_sales)

# 4.3 Drop rows with NaN
df4_3_dropped = df_sales.dropna()

print("Missing Values:")
print(missing_counts4_1)

print("\nFilled Data:")
print(df4_2_filled.head())

print("\nDropped NaN Rows:")
print(df4_3_dropped.head())


# =====================================================
# Task 5: Data Manipulation
# =====================================================
print("\n--- Task 5 ---")

# 5.1 Total Revenue
df_sales["Total_Revenue"] = df_sales["Sales"] * df_sales["Quantity"]

# 5.2 Sort by Date ascending and Sales descending
df5_2_sorted = df_sales.sort_values(
    by=["Date", "Sales"],
    ascending=[True, False]
)

# 5.3 Group by Region
df5_3_grouped_region = df_sales.groupby("Region")[["Sales", "Quantity"]].sum()

# 5.4 Group by Product
df5_4_grouped_product = df_sales.groupby("Product")["Sales"].mean()

print("\nData with Total Revenue:")
print(df_sales.head())

print("\nSorted Data:")
print(df5_2_sorted.head())

print("\nGrouped by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)

--- Intermediate Pandas Exercise ---
------------------------------------

--- Task 1 ---
Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[77 91 49 92]
 [17 19 77 39]
 [80 27 11 89]]

DataFrame:
    A   B   C   D
0  77  91  49  92
1  17  19  77  39
2  80  27  11  89

--- Task 2 ---
        Date Region   Product  Sales  Quantity
0 2023-01-01   West    Laptop  582.0       7.0
1 2023-01-02  North  Keyboard  672.0       2.0
2 2023-01-03  North   Monitor  177.0       NaN
3 2023-01-04  South    Laptop  542.0       5.0
4 2023-01-05  North  Keyboard  621.0       1.0

--- Task 3 ---
  Region  Sales
0   West  582.0
1  North  672.0
2  North  177.0
3  South  542.0
4  North  621.0
         Date Region Product  Sales  Quantity
0  2023-01-01   West  Laptop  582.0       7.0
3  2023-01-04  South  Laptop  542.0       5.0
10 2023-01-11  South  Laptop    NaN       9.0
11 2023-01-12   West  Laptop  983.0       7.0
13 2023-01-14  North  Laptop  595.0       2.0
         Date Regio